# Generated by Django 4.1.2 on 2023-02-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_tag_companies_company_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='Images/upload/logo'),
        ),
    ]
