# Generated by Django 4.1.2 on 2023-03-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(related_name='company', to='home.category'),
        ),
    ]
